### ISSUE TITLE
EDA: Add featured variables

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/MicrobiomeWorkflow#12]
Featured variables in the EDA are variables that always live at the top of the variable picker in their own special box, so that it's easy for a user to see them (and star them) immediately. This view of featured variables is the same wherever the variable picker is seen - from the Subset to the Visualize to the Downloads tab.

The way we're doing it right now is that each study has it's own list of featured variables. From Danica:
"I’m not sure if the way clinepi does it will work for mbio. We have an annotation property in the .owl for each study, which is called “is_featured”. we leave this blank for terms that are NOT featured, and fill in “yes” for variables that we want featured"

Doing this for mbio would address the goal of "pre-starring" variables that we think are interesting.

**Comment by asizemore** [comment]
Slack discussion on how to do this started [here](https://epvb.slack.com/archives/C03B93PANTA/p1649345930555619)

**Comment by wbazant** [comment]
I'm going to feature one variable, EUPATH_0011996::Sample type, because it's my favourite variable, and I'll link the commit here so that it's clear how to do it.

If there's ever a variable V in studies S and S', such that V should be featured in S but not in S', then it's gonna be a problem because we have no technology allowing that. But otherwise you'll just be able to feature whatever variables you want!

**Comment by asizemore** [comment]
Thanks @wbazant !! Sounds like a great plan!

> If there's ever a variable V in studies S and S', such that V should be featured in S but not in S', then it's gonna be a problem because we have no technology allowing that.

Ooh good to know, thank you. Tagging @dpbisme as an fyi

**Comment by asizemore** [comment]
I'm not seeing the featured var on any study. @dpbisme do you?

**Comment by asizemore** [comment]
Not crucial for beta release.
